name: PDCATimer
main: net.nando256.pdca.PdcaTimerPlugin
version: 1.0.0
api-version: '1.21.1'
authors: [ 'nando256' ]
description: 'Automatically run PDCA timers when a [PDCA] book is placed on a lectern.'
permissions:
  pdcetimer.admin:
    description: 'Allows reloading the plugin configuration.'
    default: op
commands:
  pdcetimer:
    description: 'PDCATimer utility command.'
    usage: |
      /pdcetimer reload
